### ISSUE TITLE
[Feature Request]: About insulated flask and repairability

### ISSUE THREAD

**Issue by LettereUniche** [Deaadman/UniversalTweaks#5]
### Describe the Feature

Hello,

Is it possible to add a slider where you can set the duration of insulated flask in keeping liquids warm? Usually and realistically, insulated flask keeps liquids warm for about 8 hr.

Another thing i wanted to suggest was the ability to repair not only the flask, but also certain clothing (chemical boots, ballistic vest and hardhat).
Doesn't make really that much sense, but given the fact we can repair hard plastic ski boots with leather (i guess the cloth is used on the insulated layer of the boots), it seems fair for those to have the same ability.

### Benefit of the Feature

The first one allows the player to customize the duration of the insulated flask "ability" to make it more or less realistic.
The second one i guess it's just a cheat, but since we can repair ski boots, it honestly just seems fair (more useful if clothing tweaker is installed).

**Comment by Deaadman** [comment]
Customising the duration of the insulated flask is definitely something I do can down the line, but for the second one - I get where you are coming from and the logic. But repairing something like a hardhat out of leather doesn't really seem realistic in the first place, I'm assuming Hinterland didn't make them repairable because you won't be wearing these that often anyway.

Sorry for the late response also, before getting back to Universal Tweaks I have other priorities I need to work on first. Such as work, the [ModComponent SDK](https://github.com/Deaadman/ModComponentSDK) and a rewrite of [Item Rarities](https://github.com/Deaadman/ItemRarities). Thank you for your patience.

**Comment by Deaadman** [comment]
After a long period of not doing anything to this mod, I'm finally getting around to checking off a bunch of things off my list. One of them include being able to change how long insulated flasks keep the contents inside warm.

You can check out this change [here](https://github.com/Deaadman/UniversalTweaks/commit/84f5d241950798c9f1b948e4c95773d7043da263). It will be available in the next update.

In terms of adding a recipe to repair the flask, that would require me making a ModComponent recipe and include it with this mod - so I decided to just skip it all together. Using the brand new [ModComponent SDK](https://github.com/Deaadman/ModComponentSDK) however, should allow you to easily add this recipe yourself without any coding knowledge required.

Thank you for your request and I can't wait for your feedback!
